# Generated by Django 4.1.6 on 2023-02-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('subject', models.CharField(max_length=128)),
                ('message', models.TextField(max_length=4096)),
            ],
        ),
    ]
